apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eventing-role
  namespace: eventing-demo
rules:
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - get
    - list
    - watch