apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eventing-sa:eventing-role
  namespace: eventing-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: <role>
subjects:
- kind: ServiceAccount
  name: eventing-sa
  namespace: eventing-demo