apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: cloudevents-player-trigger
spec:
  broker: default
  filters:
  - any:
    - suffix:
        type: dev.knative
    - exact:
        type: com.example.color.change
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: cloudevents-player